/**
 * GitHub PR Script Generator - Core template engine and data structures
 */

export interface ScriptConfig {
  // Repository details
  repoUrl: string;
  baseBranch: string;
  featureBranch: string;
  
  // PR details
  prTitle: string;
  prDescription: string;
  
  // Git workflow
  commitMessage: string;
  pushOptions: string[];
  
  // Authentication
  authMethod: 'github-cli' | 'pat' | 'ssh';
  patToken?: string;
  
  // Options
  createBranch: boolean;
  stageFiles: boolean;
  forcePush: boolean;
}

export interface TemplateModule {
  name: string;
  description: string;
  generate: (config: ScriptConfig) => string;
  validate: (config: ScriptConfig) => string[];
}

export interface GeneratedScript {
  content: string;
  filename: string;
  errors: string[];
  warnings: string[];
}

export class GitHubPrScriptGenerator {
  private modules: Map<string, TemplateModule> = new Map();

  registerModule(id: string, module: TemplateModule): void {
    this.modules.set(id, module);
  }

  generateScript(config: ScriptConfig): GeneratedScript {
    const errors: string[] = [];
    const warnings: string[] = [];
    
    // Validate configuration
    const configErrors = this.validateConfig(config);
    errors.push(...configErrors);
    
    if (errors.length > 0) {
      return {
        content: '',
        filename: 'create-pr.sh',
        errors,
        warnings
      };
    }

    // Generate script parts
    const scriptParts: string[] = [
      '#!/bin/bash',
      'set -e',
      '',
      '# GitHub PR Creation Script',
      '# Generated by QA Utils',
      ''
    ];

    // Add modules in order
    const moduleOrder = ['prerequisites', 'auth', 'branch', 'commit', 'push', 'pr'];
    
    for (const moduleId of moduleOrder) {
      const module = this.modules.get(moduleId);
      if (module) {
        const moduleErrors = module.validate(config);
        if (moduleErrors.length > 0) {
          errors.push(...moduleErrors);
          continue;
        }
        
        scriptParts.push(`# ${module.description}`);
        scriptParts.push(module.generate(config));
        scriptParts.push('');
      }
    }

    return {
      content: scriptParts.join('\n'),
      filename: `create-pr-${config.featureBranch}.sh`,
      errors,
      warnings
    };
  }

  private validateConfig(config: ScriptConfig): string[] {
    const errors: string[] = [];
    
    if (!config.repoUrl) errors.push('Repository URL is required');
    if (!config.baseBranch) errors.push('Base branch is required');
    if (!config.featureBranch) errors.push('Feature branch is required');
    if (!config.prTitle) errors.push('PR title is required');
    if (!config.authMethod) errors.push('Authentication method is required');
    
    if (config.authMethod === 'pat' && !config.patToken) {
      errors.push('Personal Access Token is required for PAT authentication');
    }
    
    return errors;
  }
}

// Template Modules
export const prerequisitesModule: TemplateModule = {
  name: 'Prerequisites Check',
  description: 'Check required tools and setup',
  generate: (config: ScriptConfig) => `
# Check prerequisites
command -v git >/dev/null 2>&1 || { echo "Git is required but not installed. Aborting." >&2; exit 1; }
${config.authMethod === 'github-cli' ? 'command -v gh >/dev/null 2>&1 || { echo "GitHub CLI is required but not installed. Aborting." >&2; exit 1; }' : ''}
${config.authMethod === 'github-cli' ? 'gh auth status >/dev/null 2>&1 || { echo "GitHub CLI not authenticated. Run: gh auth login" >&2; exit 1; }' : ''}

echo "✓ Prerequisites check passed"`,
  validate: () => []
};

export const authModule: TemplateModule = {
  name: 'Authentication Setup',
  description: 'Configure authentication method',
  generate: (config: ScriptConfig) => {
    switch (config.authMethod) {
      case 'github-cli':
        return '# Using GitHub CLI authentication\necho "✓ Using GitHub CLI authentication"';
      case 'pat':
        return `# Using Personal Access Token\nexport GITHUB_TOKEN="${config.patToken}"\necho "✓ Using Personal Access Token authentication"`;
      case 'ssh':
        return '# Using SSH authentication\necho "✓ Using SSH authentication"';
      default:
        return '# No authentication configured';
    }
  },
  validate: (config: ScriptConfig) => {
    if (config.authMethod === 'pat' && !config.patToken) {
      return ['Personal Access Token is required for PAT authentication'];
    }
    return [];
  }
};

export const branchModule: TemplateModule = {
  name: 'Branch Management',
  description: 'Create and switch to feature branch',
  generate: (config: ScriptConfig) => `
# Branch management
git fetch origin
${config.createBranch ? `
if git show-ref --verify --quiet refs/heads/${config.featureBranch}; then
  echo "Branch ${config.featureBranch} already exists, switching to it"
  git checkout ${config.featureBranch}
else
  echo "Creating new branch: ${config.featureBranch}"
  git checkout -b ${config.featureBranch} origin/${config.baseBranch}
fi` : `git checkout ${config.featureBranch}`}

echo "✓ On branch: ${config.featureBranch}"`,
  validate: () => []
};

export const commitModule: TemplateModule = {
  name: 'Commit Changes',
  description: 'Stage and commit changes',
  generate: (config: ScriptConfig) => `
# Commit changes
${config.stageFiles ? 'git add .' : '# Files already staged'}
${config.commitMessage ? `git commit -m "${config.commitMessage}"` : 'echo "No commit message provided, skipping commit"'}

echo "✓ Changes committed"`,
  validate: () => []
};

export const pushModule: TemplateModule = {
  name: 'Push Branch',
  description: 'Push branch to remote repository',
  generate: (config: ScriptConfig) => {
    const pushCmd = ['git push'];
    if (config.forcePush) pushCmd.push('--force');
    if (config.pushOptions.length > 0) pushCmd.push(...config.pushOptions);
    pushCmd.push(`origin ${config.featureBranch}`);
    
    return `
# Push branch to remote
${pushCmd.join(' ')}

echo "✓ Branch pushed to remote"`;
  },
  validate: () => []
};

export const prModule: TemplateModule = {
  name: 'Create Pull Request',
  description: 'Create GitHub pull request',
  generate: (config: ScriptConfig) => {
    const repoPath = config.repoUrl.replace(/^https:\/\/github\.com\//, '').replace(/\.git$/, '');
    
    switch (config.authMethod) {
      case 'github-cli':
        return `
# Create pull request using GitHub CLI
gh pr create \\
  --title "${config.prTitle}" \\
  --body "${config.prDescription}" \\
  --base ${config.baseBranch} \\
  --head ${config.featureBranch}

echo "✓ Pull request created successfully"`;
      
      case 'pat':
        return `
# Create pull request using GitHub API
curl -X POST \\
  -H "Authorization: token $GITHUB_TOKEN" \\
  -H "Accept: application/vnd.github.v3+json" \\
  https://api.github.com/repos/${repoPath}/pulls \\
  -d '{
    "title": "${config.prTitle}",
    "body": "${config.prDescription}",
    "head": "${config.featureBranch}",
    "base": "${config.baseBranch}"
  }'

echo "✓ Pull request created via API"`;
      
      default:
        return `
# Manual PR creation required
echo "Please create the pull request manually at:"
echo "https://github.com/${repoPath}/compare/${config.baseBranch}...${config.featureBranch}"`;
    }
  },
  validate: () => []
};

// Initialize generator with modules
export function createGenerator(): GitHubPrScriptGenerator {
  const generator = new GitHubPrScriptGenerator();
  
  generator.registerModule('prerequisites', prerequisitesModule);
  generator.registerModule('auth', authModule);
  generator.registerModule('branch', branchModule);
  generator.registerModule('commit', commitModule);
  generator.registerModule('push', pushModule);
  generator.registerModule('pr', prModule);
  
  return generator;
}

// Default configuration
export const defaultConfig: ScriptConfig = {
  repoUrl: '',
  baseBranch: 'main',
  featureBranch: '',
  prTitle: '',
  prDescription: '',
  commitMessage: '',
  pushOptions: [],
  authMethod: 'github-cli',
  createBranch: true,
  stageFiles: true,
  forcePush: false
};
